export interface Car {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number;
  condition: "New" | "Used" | "Certified Pre-Owned";
  bodyStyle: string;
  passengers: number;
  mpg?: string;
  range?: string;
  engine: string;
  horsepower: number;
  transmission: string;
  drivetrain: string;
  origin: string;
  color: string;
  interiorColor: string;
  interiorMaterial: string;
  features: string[];
  performance: string;
  category: string;
  image: string;
  matchScore?: number;
  description: string;
  pros: string[];
  cons: string[];
  trending?: boolean;
}

const manufacturerUrls: Record<string, string> = {
  Toyota: "https://www.toyota.com",
  Honda: "https://www.honda.com",
  Tesla: "https://www.tesla.com",
  Ford: "https://www.ford.com",
  BMW: "https://www.bmwusa.com",
  "Mercedes-Benz": "https://www.mbusa.com",
  Chevrolet: "https://www.chevrolet.com",
  Kia: "https://www.kia.com/us",
  Jeep: "https://www.jeep.com",
  Porsche: "https://www.porsche.com/usa",
  Hyundai: "https://www.hyundaiusa.com",
  Subaru: "https://www.subaru.com",
  RAM: "https://www.ramtrucks.com",
  Rivian: "https://www.rivian.com",
  Mazda: "https://www.mazdausa.com",
  Volvo: "https://www.volvocars.com/us",
  Lexus: "https://www.lexus.com",
  Audi: "https://www.audiusa.com",
  Genesis: "https://www.genesis.com/us",
  "Land Rover": "https://www.landroverusa.com",
  Ferrari: "https://www.ferrari.com/en-US",
  Nissan: "https://www.nissanusa.com",
};

export function getManufacturerUrl(make: string): string {
  return manufacturerUrls[make] ?? `https://www.google.com/search?q=${encodeURIComponent(make + " official site")}`;
}

export function getDealerSearchUrl(car: Car): string {
  const q = encodeURIComponent(`${car.year} ${car.make} ${car.model}`);
  return `https://www.cars.com/shopping/results/?keyword=${q}&stock_type=all`;
}

export function getCarGurusUrl(car: Car): string {
  const make = encodeURIComponent(car.make.toLowerCase().replace(/[-\s]/g, "_"));
  const model = encodeURIComponent(car.model.toLowerCase().replace(/[-\s/]/g, "_").split(" ")[0]);
  return `https://www.cargurus.com/Cars/new/nl?zip=&trim=&mileage=&sortDir=ASC&action=search&types%5B%5D=${car.condition === "New" ? "new" : "used"}`;
}

export const cars: Car[] = [
  {
    id: "2024-toyota-camry-xse",
    make: "Toyota",
    model: "Camry XSE",
    year: 2024,
    price: 34000,
    condition: "New",
    bodyStyle: "Sedan",
    passengers: 5,
    mpg: "28/39",
    engine: "Gas - 4-Cylinder",
    horsepower: 203,
    transmission: "Automatic",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Midnight Black",
    interiorColor: "Black",
    interiorMaterial: "Leather",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Navigation", "Powered Seats"],
    performance: "Comfort",
    category: "Sedan",
    image: "/images/cars/camry.jpg",
    description: "The Toyota Camry XSE blends sporty styling with legendary reliability. A perennial bestseller for good reason.",
    pros: ["Outstanding reliability", "Fuel efficient", "Comfortable ride", "Strong resale value"],
    cons: ["Less cargo space than SUVs", "Not as exciting to drive"],
    trending: true,
  },
  {
    id: "2024-honda-accord-sport",
    make: "Honda",
    model: "Accord Sport",
    year: 2024,
    price: 32500,
    condition: "New",
    bodyStyle: "Sedan",
    passengers: 5,
    mpg: "29/37",
    engine: "Gas - 4-Cylinder",
    horsepower: 192,
    transmission: "Automatic",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Sonic Gray Pearl",
    interiorColor: "Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Navigation"],
    performance: "Comfort",
    category: "Sedan",
    image: "/images/cars/accord.jpg",
    description: "Honda's flagship sedan offers class-leading interior space, tech features, and refined dynamics.",
    pros: ["Spacious interior", "Excellent fuel economy", "Refined handling", "Great tech features"],
    cons: ["Firm ride on rough roads", "Some find styling bland"],
    trending: false,
  },
  {
    id: "2024-tesla-model-3",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    price: 42990,
    condition: "New",
    bodyStyle: "Sedan",
    passengers: 5,
    range: "341 miles",
    engine: "Electric",
    horsepower: 283,
    transmission: "Single-Speed",
    drivetrain: "RWD",
    origin: "USA",
    color: "Pearl White",
    interiorColor: "White",
    interiorMaterial: "Faux Leather",
    features: ["Navigation", "Backup Camera", "Heated Seats", "Powered Seats", "Premium Sound", "Panoramic Sunroof"],
    performance: "Sport",
    category: "Sedan",
    image: "/images/cars/model3.jpg",
    description: "The Tesla Model 3 redefines what a sedan can be with cutting-edge technology and exhilarating performance.",
    pros: ["No gas costs", "Incredible acceleration", "Over-the-air updates", "Minimalist interior"],
    cons: ["Charging infrastructure dependency", "Polarizing interior design", "Firm ride"],
    trending: true,
  },
  {
    id: "2024-ford-f150",
    make: "Ford",
    model: "F-150 XLT",
    year: 2024,
    price: 45000,
    condition: "New",
    bodyStyle: "Truck",
    passengers: 5,
    mpg: "20/26",
    engine: "Gas - V6",
    horsepower: 400,
    transmission: "Automatic",
    drivetrain: "4WD",
    origin: "USA",
    color: "Oxford White",
    interiorColor: "Medium Earth Gray",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Navigation", "Powered Windows"],
    performance: "Off-road",
    category: "Truck",
    image: "/images/cars/f150.jpg",
    description: "America's best-selling truck for 47 years running. Built tough for work and play alike.",
    pros: ["Best-in-class towing", "Versatile bed configurations", "Comfortable cabin", "Huge dealer network"],
    cons: ["Large footprint", "Lower fuel economy", "Expensive options"],
    trending: true,
  },
  {
    id: "2024-toyota-rav4-hybrid",
    make: "Toyota",
    model: "RAV4 Hybrid",
    year: 2024,
    price: 37500,
    condition: "New",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "41/38",
    engine: "Hybrid (Gas/Plug-in)",
    horsepower: 219,
    transmission: "CVT",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Magnetic Gray",
    interiorColor: "Black",
    interiorMaterial: "Leather",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Navigation", "Powered Seats"],
    performance: "Eco-friendly",
    category: "SUV",
    image: "/images/cars/rav4.jpg",
    description: "The RAV4 Hybrid is the perfect blend of practicality, efficiency, and capability.",
    pros: ["Exceptional fuel economy", "AWD standard", "Spacious interior", "Reliable"],
    cons: ["CVT transmission feel", "Loud at highway speeds"],
    trending: true,
  },
  {
    id: "2024-bmw-3-series",
    make: "BMW",
    model: "3 Series 330i",
    year: 2024,
    price: 47900,
    condition: "New",
    bodyStyle: "Sedan",
    passengers: 5,
    mpg: "26/36",
    engine: "Gas - 4-Cylinder",
    horsepower: 255,
    transmission: "Automatic",
    drivetrain: "RWD",
    origin: "Germany",
    color: "Alpine White",
    interiorColor: "Black",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Sunroof/Moonroof"],
    performance: "Sport",
    category: "Luxury Sedan",
    image: "/images/cars/bmw3.jpg",
    description: "The benchmark sports sedan. Razor-sharp handling meets German luxury craftsmanship.",
    pros: ["Driver-focused dynamics", "Premium interior", "Powerful engine", "Prestige badge"],
    cons: ["Expensive maintenance", "Iffy infotainment UI", "Stiff ride"],
    trending: false,
  },
  {
    id: "2024-mercedes-gle",
    make: "Mercedes-Benz",
    model: "GLE 350",
    year: 2024,
    price: 62000,
    condition: "New",
    bodyStyle: "SUV - Large",
    passengers: 7,
    mpg: "21/28",
    engine: "Gas - 4-Cylinder",
    horsepower: 255,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Germany",
    color: "Iridium Silver",
    interiorColor: "Macchiato Beige",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Panoramic Sunroof"],
    performance: "Comfort",
    category: "Luxury SUV",
    image: "/images/cars/gle.jpg",
    description: "Mercedes-Benz GLE combines opulent luxury with genuine capability in a commanding SUV package.",
    pros: ["Sumptuous interior", "Smooth ride", "Powerful engine options", "3rd row available"],
    cons: ["High price", "Complex tech interface", "Expensive options"],
    trending: false,
  },
  {
    id: "2024-chevrolet-silverado",
    make: "Chevrolet",
    model: "Silverado 1500 LT",
    year: 2024,
    price: 43500,
    condition: "New",
    bodyStyle: "Truck",
    passengers: 5,
    mpg: "19/23",
    engine: "Gas - V8",
    horsepower: 355,
    transmission: "Automatic",
    drivetrain: "4WD",
    origin: "USA",
    color: "Rally Green",
    interiorColor: "Jet Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Powered Windows"],
    performance: "Off-road",
    category: "Truck",
    image: "/images/cars/silverado.jpg",
    description: "The Silverado 1500 delivers workhorse capability with an increasingly refined interior experience.",
    pros: ["V8 power", "Strong towing capacity", "Wide dealer network", "Comfortable cabin"],
    cons: ["Lower fuel economy", "Firm ride off-highway"],
    trending: false,
  },
  {
    id: "2023-honda-civic-hatchback",
    make: "Honda",
    model: "Civic Hatchback Sport",
    year: 2023,
    price: 18500,
    condition: "Certified Pre-Owned",
    bodyStyle: "Hatchback",
    passengers: 5,
    mpg: "31/40",
    engine: "Gas - 4-Cylinder",
    horsepower: 158,
    transmission: "Automatic",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Sonic Gray Pearl",
    interiorColor: "Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Powered Windows"],
    performance: "Eco-friendly",
    category: "Hatchback",
    image: "/images/cars/civic.jpg",
    description: "The Civic Hatchback adds cargo versatility to Honda's beloved compact formula.",
    pros: ["Excellent fuel economy", "Spacious for the class", "Reliable", "Affordable"],
    cons: ["Less powerful", "Basic interior materials"],
    trending: false,
  },
  {
    id: "2024-ford-mustang",
    make: "Ford",
    model: "Mustang GT",
    year: 2024,
    price: 42500,
    condition: "New",
    bodyStyle: "Coupe - 2-Door",
    passengers: 4,
    mpg: "15/24",
    engine: "Gas - V8",
    horsepower: 480,
    transmission: "Manual",
    drivetrain: "RWD",
    origin: "USA",
    color: "Grabber Blue",
    interiorColor: "Ebony",
    interiorMaterial: "Leather",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Premium Sound"],
    performance: "Sport",
    category: "Muscle Car",
    image: "/images/cars/mustang.jpg",
    description: "An American icon. The Mustang GT's 5.0L V8 delivers spine-tingling performance and legendary style.",
    pros: ["Thrilling V8 sound", "Iconic styling", "Fun to drive", "Manual option"],
    cons: ["Poor fuel economy", "Rear visibility", "Stiff ride"],
    trending: true,
  },
  {
    id: "2024-volvo-xc90",
    make: "Volvo",
    model: "XC90 Recharge",
    year: 2024,
    price: 72000,
    condition: "New",
    bodyStyle: "SUV - Large",
    passengers: 7,
    mpg: "56 MPGe",
    engine: "Hybrid (Gas/Plug-in)",
    horsepower: 455,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Sweden",
    color: "Crystal White",
    interiorColor: "Blonde",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Panoramic Sunroof"],
    performance: "Comfort",
    category: "Luxury SUV",
    image: "/images/cars/xc90.jpg",
    description: "Volvo's flagship SUV marries Scandinavian elegance with class-leading safety technology.",
    pros: ["Gorgeous interior", "Best-in-class safety", "3rd row seating", "Plugin hybrid efficiency"],
    cons: ["Costly", "Infotainment learning curve", "Heavy"],
    trending: false,
  },
  {
    id: "2024-kia-ev6",
    make: "Kia",
    model: "EV6 Wind",
    year: 2024,
    price: 46900,
    condition: "New",
    bodyStyle: "Hatchback",
    passengers: 5,
    range: "310 miles",
    engine: "Electric",
    horsepower: 225,
    transmission: "Single-Speed",
    drivetrain: "RWD",
    origin: "Korea",
    color: "Snow White Pearl",
    interiorColor: "Pebble Gray",
    interiorMaterial: "Faux Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound"],
    performance: "Eco-friendly",
    category: "Electric",
    image: "/images/cars/ev6.jpg",
    description: "Kia's award-winning EV6 combines striking design with ultra-fast 800V charging and sporty dynamics.",
    pros: ["800V fast charging", "Award-winning design", "Long range", "Fun to drive"],
    cons: ["Kia brand perception", "Limited service centers"],
    trending: true,
  },
  {
    id: "2022-jeep-wrangler",
    make: "Jeep",
    model: "Wrangler Rubicon",
    year: 2022,
    price: 42000,
    condition: "Used",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "17/22",
    engine: "Gas - 4-Cylinder",
    horsepower: 270,
    transmission: "Automatic",
    drivetrain: "4WD",
    origin: "USA",
    color: "Firecracker Red",
    interiorColor: "Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats"],
    performance: "Off-road",
    category: "Off-road SUV",
    image: "/images/cars/wrangler.jpg",
    description: "The ultimate off-road icon. Wrangler Rubicon tackles anything nature throws at it.",
    pros: ["Legendary off-road capability", "Removable doors/roof", "Iconic style", "Strong community"],
    cons: ["Poor highway fuel economy", "Rough on-road ride", "Wind noise"],
    trending: false,
  },
  {
    id: "2024-porsche-911",
    make: "Porsche",
    model: "911 Carrera",
    year: 2024,
    price: 115000,
    condition: "New",
    bodyStyle: "Coupe - 2-Door",
    passengers: 4,
    mpg: "18/24",
    engine: "Gas - 4-Cylinder",
    horsepower: 379,
    transmission: "Automatic",
    drivetrain: "RWD",
    origin: "Germany",
    color: "Guards Red",
    interiorColor: "Black",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Sunroof/Moonroof"],
    performance: "Sport",
    category: "Sports Car",
    image: "/images/cars/911.jpg",
    description: "The 911 is the gold standard of sports cars — thrilling performance wrapped in timeless design.",
    pros: ["Best handling available", "Timeless design", "Surprisingly practical", "Incredible resale"],
    cons: ["Very expensive", "Tight rear seats", "Options inflate price massively"],
    trending: false,
  },
  {
    id: "2024-hyundai-ioniq5",
    make: "Hyundai",
    model: "IONIQ 5 SE Standard Range",
    year: 2024,
    price: 41450,
    condition: "New",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    range: "220 miles",
    engine: "Electric",
    horsepower: 168,
    transmission: "Single-Speed",
    drivetrain: "RWD",
    origin: "Korea",
    color: "Atlas White",
    interiorColor: "Dark Pebble Gray",
    interiorMaterial: "Faux Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats"],
    performance: "Eco-friendly",
    category: "Electric SUV",
    image: "/images/cars/ioniq5.jpg",
    description: "The IONIQ 5's retro-futuristic design and ultra-fast charging make it one of EVs most compelling.",
    pros: ["Stunning design", "800V ultra-fast charging", "Spacious interior", "Vehicle-to-load capability"],
    cons: ["Standard range is limited", "Heavy"],
    trending: true,
  },
  {
    id: "2024-subaru-outback",
    make: "Subaru",
    model: "Outback Premium",
    year: 2024,
    price: 31000,
    condition: "New",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "26/33",
    engine: "Gas - 4-Cylinder",
    horsepower: 182,
    transmission: "CVT",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Geyser Blue",
    interiorColor: "Warm Ivory",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Navigation"],
    performance: "Off-road",
    category: "Crossover SUV",
    image: "/images/cars/outback.jpg",
    description: "Subaru's iconic adventure-ready wagon/SUV hybrid with symmetrical AWD standard on every trim.",
    pros: ["AWD standard", "Ground clearance", "Reliable", "Practical"],
    cons: ["CVT feel", "Underpowered", "Dated infotainment"],
    trending: false,
  },
  {
    id: "2024-toyota-sienna",
    make: "Toyota",
    model: "Sienna XSE",
    year: 2024,
    price: 47000,
    condition: "New",
    bodyStyle: "Van/Minivan",
    passengers: 8,
    mpg: "36/36",
    engine: "Hybrid (Gas/Plug-in)",
    horsepower: 245,
    transmission: "CVT",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Wind Chill Pearl",
    interiorColor: "Graphite",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats", "Sunroof/Moonroof", "Premium Sound"],
    performance: "Comfort",
    category: "Minivan",
    image: "/images/cars/sienna.jpg",
    description: "The only hybrid minivan available, combining family practicality with outstanding fuel efficiency.",
    pros: ["Best fuel economy in class", "AWD standard", "Extremely practical", "Smooth ride"],
    cons: ["Minivan stigma", "Not exciting to drive", "High price for the segment"],
    trending: false,
  },
  {
    id: "2023-mazda-cx5",
    make: "Mazda",
    model: "CX-5 Carbon Edition",
    year: 2023,
    price: 24500,
    condition: "Certified Pre-Owned",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "25/31",
    engine: "Gas - 4-Cylinder",
    horsepower: 187,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Machine Gray",
    interiorColor: "Black",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats"],
    performance: "Comfort",
    category: "Compact SUV",
    image: "/images/cars/cx5.jpg",
    description: "Mazda's premium compact SUV offers near-luxury refinement at a mainstream price point.",
    pros: ["Premium feel for the price", "Fun to drive", "Quiet cabin", "Sharp styling"],
    cons: ["Tight rear cargo", "No third row", "Base engine can feel slow"],
    trending: false,
  },
  {
    id: "2024-ram-1500",
    make: "RAM",
    model: "1500 Laramie",
    year: 2024,
    price: 58000,
    condition: "New",
    bodyStyle: "Truck",
    passengers: 5,
    mpg: "17/24",
    engine: "Gas - V8",
    horsepower: 395,
    transmission: "Automatic",
    drivetrain: "4WD",
    origin: "USA",
    color: "Diamond Black",
    interiorColor: "Mountain Brown",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Sunroof/Moonroof"],
    performance: "Off-road",
    category: "Luxury Truck",
    image: "/images/cars/ram1500.jpg",
    description: "The RAM 1500 Laramie elevates the pickup truck to near-luxury standards with its Multifunction tailgate and air suspension.",
    pros: ["Best-in-class interior quality", "Air suspension", "Coil spring rear", "Powerful options"],
    cons: ["Fuel economy", "Expensive as tested", "Large size"],
    trending: false,
  },
  {
    id: "2021-bmw-x5",
    make: "BMW",
    model: "X5 xDrive40i",
    year: 2021,
    price: 52000,
    condition: "Certified Pre-Owned",
    bodyStyle: "SUV - Large",
    passengers: 7,
    mpg: "21/26",
    engine: "Gas - 6-Cylinder",
    horsepower: 335,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Germany",
    color: "Mineral White",
    interiorColor: "Mocha",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Panoramic Sunroof"],
    performance: "Sport",
    category: "Luxury SUV",
    image: "/images/cars/x5.jpg",
    description: "The BMW X5 redefines what an SUV can do — combining athletic performance with genuine luxury.",
    pros: ["Exceptional driving dynamics", "Powerful inline-6", "Luxurious interior", "Optional 3rd row"],
    cons: ["Expensive maintenance", "Complex iDrive", "Firm ride"],
    trending: false,
  },
  {
    id: "2024-rivian-r1t",
    make: "Rivian",
    model: "R1T Dual-Motor",
    year: 2024,
    price: 74000,
    condition: "New",
    bodyStyle: "Truck",
    passengers: 5,
    range: "314 miles",
    engine: "Electric",
    horsepower: 600,
    transmission: "Single-Speed",
    drivetrain: "AWD",
    origin: "USA",
    color: "Launch Green",
    interiorColor: "Forest Edge",
    interiorMaterial: "Faux Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound"],
    performance: "Off-road",
    category: "Electric Truck",
    image: "/images/cars/r1t.jpg",
    description: "Rivian's R1T is the world's first mass-produced electric adventure truck — and it's a revelation.",
    pros: ["Off-road capable EV", "Gear tunnel storage", "Impressive range", "Quad-motor available"],
    cons: ["Service network growing", "Software quirks", "Expensive"],
    trending: true,
  },
  {
    id: "2024-mazda-miata",
    make: "Mazda",
    model: "MX-5 Miata Grand Touring",
    year: 2024,
    price: 37000,
    condition: "New",
    bodyStyle: "Convertible",
    passengers: 2,
    mpg: "26/34",
    engine: "Gas - 4-Cylinder",
    horsepower: 181,
    transmission: "Manual",
    drivetrain: "RWD",
    origin: "Japan",
    color: "Soul Red Crystal",
    interiorColor: "Red",
    interiorMaterial: "Leather",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats", "Premium Sound"],
    performance: "Sport",
    category: "Sports Car",
    image: "/images/cars/miata.jpg",
    description: "Pure driving joy in its most distilled form. The Miata is the world's best-selling two-seat roadster.",
    pros: ["Ultimate driving experience", "Reliable", "Affordable for a sports car", "Manual transmission"],
    cons: ["Only 2 seats", "Tiny trunk", "Limited power"],
    trending: false,
  },
  {
    id: "2024-chevy-bolt-ev",
    make: "Chevrolet",
    model: "Bolt EV 2LT",
    year: 2024,
    price: 27495,
    condition: "New",
    bodyStyle: "Hatchback",
    passengers: 5,
    range: "259 miles",
    engine: "Electric",
    horsepower: 200,
    transmission: "Single-Speed",
    drivetrain: "FWD",
    origin: "USA",
    color: "Riptide Blue",
    interiorColor: "Jet Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Navigation"],
    performance: "Eco-friendly",
    category: "Electric",
    image: "/images/cars/bolt.jpg",
    description: "America's most affordable EV offers 259 miles of range and DC fast charging at an unbeatable price.",
    pros: ["Most affordable EV", "Practical hatchback", "Good range", "Low running costs"],
    cons: ["DC fast charge slower than competitors", "Plain interior"],
    trending: false,
  },
  {
    id: "2023-lexus-rx350",
    make: "Lexus",
    model: "RX 350 F Sport",
    year: 2023,
    price: 58000,
    condition: "Certified Pre-Owned",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "22/29",
    engine: "Gas - 4-Cylinder",
    horsepower: 275,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Cloudburst Gray",
    interiorColor: "Rioja Red",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Sunroof/Moonroof"],
    performance: "Comfort",
    category: "Luxury SUV",
    image: "/images/cars/rx350.jpg",
    description: "Lexus's best-selling RX combines legendary reliability with luxury refinement.",
    pros: ["Outstanding reliability", "Refined interior", "Strong resale", "Comfortable"],
    cons: ["Not as sporty as rivals", "Touch-sensitive controls"],
    trending: false,
  },
  {
    id: "2024-audi-q5",
    make: "Audi",
    model: "Q5 45 TFSI",
    year: 2024,
    price: 52000,
    condition: "New",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "23/29",
    engine: "Gas - 4-Cylinder",
    horsepower: 261,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Germany",
    color: "Mythos Black",
    interiorColor: "Atlas Beige",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Sunroof/Moonroof"],
    performance: "Sport",
    category: "Luxury SUV",
    image: "/images/cars/q5.jpg",
    description: "Audi's Q5 sets the standard for the premium compact SUV segment with its understated elegance.",
    pros: ["Excellent build quality", "Available quattro AWD", "Refined ride", "Beautiful interior"],
    cons: ["Expensive options", "Tight 3rd row if optioned", "High running costs"],
    trending: false,
  },
  {
    id: "2020-toyota-corolla",
    make: "Toyota",
    model: "Corolla LE",
    year: 2020,
    price: 14500,
    condition: "Used",
    bodyStyle: "Sedan",
    passengers: 5,
    mpg: "30/38",
    engine: "Gas - 4-Cylinder",
    horsepower: 139,
    transmission: "CVT",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Blue Crush Metallic",
    interiorColor: "Black",
    interiorMaterial: "Cloth",
    features: ["Backup Camera", "Powered Windows"],
    performance: "Eco-friendly",
    category: "Economy Sedan",
    image: "/images/cars/corolla.jpg",
    description: "The world's best-selling car for a reason. Reliable, efficient, and affordable.",
    pros: ["World-class reliability", "Excellent fuel economy", "Low cost of ownership", "Affordable"],
    cons: ["Underpowered", "Basic interior", "Not exciting"],
    trending: false,
  },
  {
    id: "2024-genesis-gv80",
    make: "Genesis",
    model: "GV80 2.5T",
    year: 2024,
    price: 58000,
    condition: "New",
    bodyStyle: "SUV - Large",
    passengers: 7,
    mpg: "21/25",
    engine: "Gas - 4-Cylinder",
    horsepower: 300,
    transmission: "Automatic",
    drivetrain: "AWD",
    origin: "Japan",
    color: "Savile Silver",
    interiorColor: "Terracotta",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound", "Panoramic Sunroof"],
    performance: "Comfort",
    category: "Luxury SUV",
    image: "/images/cars/gv80.jpg",
    description: "Genesis GV80 delivers German-level luxury at a more attainable price — a genuine alternative to BMW and Mercedes.",
    pros: ["Outstanding value for luxury", "Beautiful design", "Comfortable ride", "7-seat option"],
    cons: ["Brand recognition still building", "Less sporty than rivals", "Dealer network smaller"],
    trending: true,
  },
  {
    id: "2024-land-rover-defender",
    make: "Land Rover",
    model: "Defender 90",
    year: 2024,
    price: 63000,
    condition: "New",
    bodyStyle: "SUV - Compact",
    passengers: 5,
    mpg: "18/23",
    engine: "Gas - 4-Cylinder",
    horsepower: 296,
    transmission: "Automatic",
    drivetrain: "4WD",
    origin: "Britain",
    color: "Tasman Blue",
    interiorColor: "Ebony/Tan",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats", "Premium Sound"],
    performance: "Off-road",
    category: "Luxury Off-road",
    image: "/images/cars/defender.jpg",
    description: "The reimagined Defender blends rugged British heritage with modern luxury and technology.",
    pros: ["Iconic design", "Exceptional off-road", "Luxury interior", "Unique character"],
    cons: ["Known reliability issues", "Expensive", "Poor fuel economy"],
    trending: false,
  },
  {
    id: "2019-honda-odyssey",
    make: "Honda",
    model: "Odyssey EX-L",
    year: 2019,
    price: 24000,
    condition: "Used",
    bodyStyle: "Van/Minivan",
    passengers: 8,
    mpg: "19/28",
    engine: "Gas - V6",
    horsepower: 280,
    transmission: "Automatic",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Modern Steel",
    interiorColor: "Gray",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats", "Sunroof/Moonroof"],
    performance: "Comfort",
    category: "Minivan",
    image: "/images/cars/odyssey.jpg",
    description: "Honda's Odyssey remains the family van benchmark with its clever Magic Slide second-row seats.",
    pros: ["Practical family transport", "Smooth V6", "Magic Slide seats", "Reliable"],
    cons: ["No AWD", "Thirstier than Sienna", "Minivan stigma"],
    trending: false,
  },
  {
    id: "2024-ferrari-roma",
    make: "Ferrari",
    model: "Roma",
    year: 2024,
    price: 225000,
    condition: "New",
    bodyStyle: "Coupe - 2-Door",
    passengers: 4,
    mpg: "14/21",
    engine: "Gas - V8",
    horsepower: 612,
    transmission: "Automatic",
    drivetrain: "RWD",
    origin: "Italy",
    color: "Rosso Roma",
    interiorColor: "Cuoio",
    interiorMaterial: "Leather",
    features: ["Navigation", "Backup Camera", "Heated Seats", "Ventilated Seats", "Powered Seats", "Premium Sound"],
    performance: "Sport",
    category: "Supercar",
    image: "/images/cars/roma.jpg",
    description: "The Ferrari Roma is la dolce vita on wheels — a grand touring masterpiece dripping in Italian flair.",
    pros: ["Breathtaking performance", "Stunning design", "Grand touring comfort", "Exclusivity"],
    cons: ["Extremely expensive", "Costly maintenance", "Limited practicality"],
    trending: false,
  },
  {
    id: "2024-nissan-leaf",
    make: "Nissan",
    model: "LEAF SV Plus",
    year: 2024,
    price: 32400,
    condition: "New",
    bodyStyle: "Hatchback",
    passengers: 5,
    range: "212 miles",
    engine: "Electric",
    horsepower: 214,
    transmission: "Single-Speed",
    drivetrain: "FWD",
    origin: "Japan",
    color: "Brilliant Silver",
    interiorColor: "Charcoal",
    interiorMaterial: "Cloth",
    features: ["Navigation", "Backup Camera", "CarPlay/Android Auto", "Heated Seats", "Powered Seats"],
    performance: "Eco-friendly",
    category: "Electric",
    image: "/images/cars/leaf.jpg",
    description: "The world's first mass-market EV, now refined over 13 years with improved range and features.",
    pros: ["Pioneer EV brand", "Comfortable", "Available e-Pedal", "Affordable"],
    cons: ["No active thermal management", "CHAdeMO (less common)", "Limited range"],
    trending: false,
  },
];

export function getCarById(id: string): Car | undefined {
  return cars.find((car) => car.id === id);
}

export function getFilteredCars(filters: {
  budget?: string;
  bodyStyle?: string;
  passengers?: number;
  condition?: string;
  engine?: string;
  origin?: string;
  performance?: string;
  features?: string[];
}): Car[] {
  return cars.filter((car) => {
    if (filters.budget) {
      const budgetMap: Record<string, [number, number]> = {
        "Under $15k": [0, 15000],
        "$15k-$25k": [15000, 25000],
        "$25k-$40k": [25000, 40000],
        "$40k-$60k": [40000, 60000],
        "$60k-$100k": [60000, 100000],
        "$100k+": [100000, Infinity],
      };
      const range = budgetMap[filters.budget];
      if (range && (car.price < range[0] || car.price > range[1])) return false;
    }
    if (filters.bodyStyle && !car.bodyStyle.includes(filters.bodyStyle)) return false;
    if (filters.passengers && car.passengers < filters.passengers) return false;
    if (filters.condition && car.condition !== filters.condition) return false;
    if (filters.engine && !car.engine.includes(filters.engine)) return false;
    if (filters.origin && car.origin !== filters.origin) return false;
    if (filters.performance && car.performance !== filters.performance) return false;
    return true;
  });
}

export function getTrendingCars(): Car[] {
  return cars.filter((car) => car.trending);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}
